# Generated by Django 4.2.1 on 2023-06-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=200)),
                ("Task", models.CharField(max_length=200)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Complete", "Complete"),
                            ("In-Progress", "In-Progress"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
